version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
      timezone: America/Toronto
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: America/Toronto
    commit-message:
      prefix: "⬆️ "
